import cv2
import time
import os
import json
from typing import List, Dict, Any, Optional, Callable
from .engine import HyperOCREngine

class VideoTextExtractor:
    """
    SOTA 2026 Video OCR & On-Screen Text/Subtitle Extractor.
    Extracts text from MP4/MKV/AVI video files, webcam streams, and screen recordings
    with automatic scene-change detection and timestamping.
    """
    def __init__(self, engine: Optional[HyperOCREngine] = None, sample_fps: float = 2.0):
        self.engine = engine or HyperOCREngine()
        self.sample_fps = sample_fps

    def extract_from_video(
        self,
        video_path: str,
        output_format: str = "txt",
        progress_cb: Optional[Callable[[float, int], None]] = None
    ) -> List[Dict[str, Any]]:
        """
        Processes a video file and returns all timestamped text events.
        """
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            raise ValueError(f"Could not open video file: {video_path}")

        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        duration_sec = total_frames / fps if total_frames > 0 else 0
        
        # Determine frame skip step for desired sample FPS
        step = max(1, int(fps / self.sample_fps))
        
        timeline = []
        frame_idx = 0
        last_seen_text = ""
        
        while True:
            ret, frame = cap.read()
            if not ret:
                break
                
            if frame_idx % step == 0:
                timestamp_sec = frame_idx / fps
                # Run OCR with temporal differencing cache
                results, lat = self.engine.recognize(frame, use_cache=True)
                
                if results:
                    current_text = " ".join([r["text"] for r in results]).strip()
                    # Only record if text changed or new content appeared
                    if current_text and current_text != last_seen_text:
                        timestamp_str = time.strftime('%H:%M:%S', time.gmtime(timestamp_sec))
                        timeline.append({
                            "timestamp_sec": round(timestamp_sec, 2),
                            "timestamp": timestamp_str,
                            "frame": frame_idx,
                            "text": current_text,
                            "lines": [r["text"] for r in results]
                        })
                        last_seen_text = current_text
                        
                if progress_cb and total_frames > 0:
                    progress_cb(frame_idx / total_frames, len(timeline))
                    
            frame_idx += 1
            
        cap.release()
        return timeline

    @staticmethod
    def export_srt(timeline: List[Dict[str, Any]], output_path: str):
        """Export timeline to standard .srt subtitle file."""
        with open(output_path, "w", encoding="utf-8") as f:
            for idx, item in enumerate(timeline, 1):
                start_sec = item["timestamp_sec"]
                end_sec = start_sec + 2.0  # Display for 2 seconds
                
                start_srt = time.strftime('%H:%M:%S', time.gmtime(start_sec)) + f",{int((start_sec % 1) * 1000):03d}"
                end_srt = time.strftime('%H:%M:%S', time.gmtime(end_sec)) + f",{int((end_sec % 1) * 1000):03d}"
                
                f.write(f"{idx}\n{start_srt} --> {end_srt}\n{item['text']}\n\n")

    @staticmethod
    def export_transcript(timeline: List[Dict[str, Any]], output_path: str):
        """Export timeline to clean timestamped transcript."""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("# Video Text & On-Screen Transcript (Generated by HyperOCR)\n\n")
            for item in timeline:
                f.write(f"[{item['timestamp']}] {item['text']}\n")
